# 1. Create a 3x3x3 array with random values 

In [2]:
import numpy as np
print(np.random.random((3,3,3)))

[[[0.11541352 0.91344554 0.70463829]
  [0.6296027  0.60089809 0.26935253]
  [0.69373446 0.52661753 0.64645416]]

 [[0.78752427 0.87397854 0.05799578]
  [0.66506489 0.14390012 0.60941159]
  [0.49966252 0.5453928  0.04520475]]

 [[0.00685893 0.58807621 0.68337447]
  [0.46379633 0.40377631 0.5785745 ]
  [0.29914135 0.52952204 0.73637674]]]


# 2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [3]:
print(np.diag([1,2,3,4]))

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 3.Create a 8x8 matrix and fill it with a checkerboard pattern

In [6]:
m = np.zeros((8,8))
m[1::2,::2] = 1
m[::2,1::2] = 1
print(m)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


# 4. Normalize a 5x5 random matrix

In [10]:
n = np.random.random((5,5))
norm = (n - np.mean(n))/np.std(n)
print(norm)

[[ 1.3485813   0.37664471 -1.52325993 -0.17589295 -1.28804606]
 [-1.45426669 -0.6851282  -0.07933025 -0.49603232  1.08340203]
 [ 0.06555329  1.12293962  1.31815904  0.40269458 -1.28887413]
 [ 1.15788304 -0.87308014  0.22190261 -0.20030312 -1.36306122]
 [ 1.57064449  0.41787786  0.23790089 -1.2597211   1.36281267]]


# 5.  How to find common values between two arrays?

In [13]:
a = np.random.randint(0,5,5)
b = np.random.randint(0,5,5)
print(np.intersect1d(a,b))

[0 1 2]


# 6.How to get the dates of yesterday, today and tomorrow?

In [15]:
print(np.datetime64('today') - np.timedelta64(1))
print(np.datetime64('today'))
print(np.datetime64('today') + np.timedelta64(1))

2020-08-23
2020-08-24
2020-08-25


# 7. Consider two random array A and B, check if they are equal

In [16]:
e = np.random.randint(0,10,10)
r = np.random.randint(0,10,10)
print(np.array_equal(e,r))

False


# 8.Create random vector of size 10 and replace the maximum value by 0 

In [18]:
rv = np.random.random(10)
rv[rv.argmax()] = 0
print(rv)

[0.20777551 0.81522138 0.12476065 0.66510594 0.         0.77987077
 0.63657126 0.70874129 0.17046766 0.5194079 ]


# 9. How to print all the values of an array?

In [22]:
np.set_printoptions(threshold=np.inf)
z = np.random.random(10)
print(z)

[0.86530864 0.83057092 0.12420585 0.16574846 0.00855685 0.61051425
 0.09844337 0.15509538 0.16307718 0.11009819]


# 10.Subtract the mean of each row of a matrix

In [27]:
a = np.random.random((5,5))
b = a - a.mean(axis=1)
print(b)

[[-0.28733599  0.26912499  0.28993346  0.35635559  0.36299307]
 [-0.38171695 -0.27173004  0.23117929  0.24092269 -0.01470038]
 [-0.24333741 -0.35260347  0.14204784 -0.19926042 -0.15672839]
 [-0.52940607  0.12983856  0.39162376  0.03440524  0.12132249]
 [-0.16058262  0.45922001  0.33853528 -0.38026723 -0.38983328]]


# 11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? 

In [38]:
a = np.ones(5)
b = np.random.randint(0,len(a),20)
a += np.bincount(b, minlength=len(a))
np.add.at(a, b, 1)
print(a)

[ 9.  5. 11. 13.  7.]


# 12.How to get the diagonal of a dot product?

In [29]:
x = np.random.random((5,5))
y = np.random.random((5,5))

print(np.diag(np.dot(x, y)))

[1.09831994 1.54957859 2.9420059  1.44714032 1.65000002]


# 13.How to find the most frequent value in an array?

In [32]:
a = np.random.randint(0,10,20)
print(a)
print("Frequent value = ", np.bincount(a).argmax())

[7 5 3 2 8 1 9 1 5 6 8 2 1 3 9 7 4 1 5 7]
Frequent value =  1


# 14.How to get the n largest values of an array

In [34]:
a = np.arange(1000)
np.random.shuffle(a)
n = 10
print (a[np.argsort(a)[-n:]])

[990 991 992 993 994 995 996 997 998 999]


# 15.How to create a record array from a regular array?

In [35]:
a = np.array(['Hello','World'])
b = np.array([1,2])
c = np.core.records.fromarrays([a,b],names='A,B')
print(c)

[('Hello', 1) ('World', 2)]
